# Ved Motors — Data Cleaning with Pandas

This notebook contains my learning and experimentation while cleaning
a vehicle sales dataset from Ved Motors.

I used Pandas to inspect the data, identify inconsistencies, handle
missing values, clean text and date columns, and finally export the
cleaned dataset.

### Tools Used
- Python
- Pandas
- Jupyter Notebook
- OpenPyXL
- Excel

In [131]:
import pandas as pd

## 1. Loading the Dataset

First, I loaded the raw Excel file into a Pandas DataFrame.

In [132]:
df = pd.read_excel(
    r"C:\Users\Shravani Patane\Downloads\Ved_Motors_Project\2021(1)ved.xlsx"
)

df.head()

,Unnamed: 0,Booking Date,Customer Name,Mobile No.,Company,Model,Colour,Dealer,Vehical Chassis No.,Vehical Engine No.,...,Total Paid Amount,DP Balance,Disbursed Date,Disbursed Amount,Net Earning loan,Total Earning,Balance Remark,Vehical RTO No.,Date of Birth,Address
0,1,2021-10-15,SAPANA SALUNKHE,9082384445,T-V-S,JUPITER ZX,GREENISH BLUE,AUTORACE,MD626CG59M1L09923,DG5LM1802951,...,21000,0,2021-10-15 00:00:00,72290.0,5290,91290,NaN,MH04KZ6980,1980-08-12,NaN
1,2,2021-10-15,HEMANGI SHELAR,9869658575,BGUSS E,BGUS A2,GREY,BGUSS,A21BG000079,BBD00103,...,68500,0,NaN,NaN,0,2200,NaN,NaN,1984-11-15,NaN
2,3,2021-12-16,ANIKET SURYWANSI,9819169457,Honda,CB SHINE,Mat Grey,VIHAN,ME4JC859JMD022325,JC85ED1063498,...,95500,0,NaN,NaN,0,3500,NaN,MH04KY7601,1999-09-18,NaN
3,4,2021-10-17,TEJAS BHURE,9702403349,Honda,CB SHINE,BLACK RED,VIHAN,ME4JC85AKMG033594,JC85EG1037927,...,89000,0,NaN,NaN,0,2000,NaN,MH04KY5509,1982-12-21,NaN
4,5,2021-10-17,SAGAR PALSE,8879417136,BGUSS E,BGUS A2,BLUE,BGUSS,A21BG000081,BBD000295,...,30000,0,0,NaN,-39000,-35300,NaN,NaN,1994-09-24,NaN

## 2. Understanding the Dataset

Before cleaning the data, I wanted to understand its size,
columns, data types and overall structure.

In [133]:
df.shape

(18, 44)

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 44 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                18 non-null     int64
 1   Booking Date              18 non-null     datetime64[ns]
 2   Customer Name             18 non-null     object
 3   Mobile No.                18 non-null     int64
 4   Company                   18 non-null     object
 5   Model                     18 non-null     object
 6   Colour                    18 non-null     object
 7   Dealer                    18 non-null     object
 8   Vehical Chassis No.       17 non-null     object
 9   Vehical Engine No.        16 non-null     object
 10  Vehical Base              18 non-null     object
 11  Dealer Price              18 non-null     int64
 12  E Payment Tax             18 non-null     int64
 13  Insurance                 18 non-null     int64
 14  Hypothication             18 non-null     int64
 15  Total Vehical Cost        18 non-null     int64
 16  Ridding Cost              18 non-null     int64
 17  Accessories               18 non-null     int64
 18  Total Cost to Ved Motors  18 non-null     int64
 19  Selling Price             18 non-null     int64
 20  Net Earning               18 non-null     int64
 21  Payment Type              18 non-null     object
 22  CASH Payment              18 non-null     int64
 23  Loan Amount               13 non-null     float64
 24  EMI Month                 14 non-null     float64
 25  EMI Amount                16 non-null     float64
 26  Receipt No.1              18 non-null     int64
 27  Booking Amount            18 non-null     int64
 28  Receipt No.2              18 non-null     int64
 29  Amount                    18 non-null     int64
 30  Receipt No.3              18 non-null     int64
 31  Amount.1                  18 non-null     int64
 32  Receipt No.4              18 non-null     int64
 33  Amount.2                  18 non-null     int64
 34  Total Paid Amount         18 non-null     int64
 35  DP Balance                18 non-null     int64
 36  Disbursed Date            4 non-null      object
 37  Disbursed Amount          8 non-null      float64
 38  Net Earning loan          18 non-null     int64
 39  Total Earning             18 non-null     int64
 40  Balance Remark            0 non-null      float64
 41  Vehical RTO No.           9 non-null      object
 42  Date of Birth             13 non-null     datetime64[ns]
 43  Address                   0 non-null      float64
dtypes: datetime64[ns](2), float64(6), int64(25), object(11)
memory usage: 6.3+ KB

In [135]:
df.head()

,Unnamed: 0,Booking Date,Customer Name,Mobile No.,Company,Model,Colour,Dealer,Vehical Chassis No.,Vehical Engine No.,...,Total Paid Amount,DP Balance,Disbursed Date,Disbursed Amount,Net Earning loan,Total Earning,Balance Remark,Vehical RTO No.,Date of Birth,Address
0,1,2021-10-15,SAPANA SALUNKHE,9082384445,T-V-S,JUPITER ZX,GREENISH BLUE,AUTORACE,MD626CG59M1L09923,DG5LM1802951,...,21000,0,2021-10-15 00:00:00,72290.0,5290,91290,NaN,MH04KZ6980,1980-08-12,NaN
1,2,2021-10-15,HEMANGI SHELAR,9869658575,BGUSS E,BGUS A2,GREY,BGUSS,A21BG000079,BBD00103,...,68500,0,NaN,NaN,0,2200,NaN,NaN,1984-11-15,NaN
2,3,2021-12-16,ANIKET SURYWANSI,9819169457,Honda,CB SHINE,Mat Grey,VIHAN,ME4JC859JMD022325,JC85ED1063498,...,95500,0,NaN,NaN,0,3500,NaN,MH04KY7601,1999-09-18,NaN
3,4,2021-10-17,TEJAS BHURE,9702403349,Honda,CB SHINE,BLACK RED,VIHAN,ME4JC85AKMG033594,JC85EG1037927,...,89000,0,NaN,NaN,0,2000,NaN,MH04KY5509,1982-12-21,NaN
4,5,2021-10-17,SAGAR PALSE,8879417136,BGUSS E,BGUS A2,BLUE,BGUSS,A21BG000081,BBD000295,...,30000,0,0,NaN,-39000,-35300,NaN,NaN,1994-09-24,NaN

## 3. Checking Missing Values

I checked each column to understand where missing values were present
before deciding how to handle them.

In [136]:
df.isnull().sum()

Unnamed: 0                   0
Booking Date                 0
Customer Name                0
Mobile No.                   0
Company                      0
Model                        0
Colour                       0
Dealer                       0
Vehical Chassis No.          1
Vehical Engine No.           2
Vehical Base                 0
Dealer Price                 0
E Payment Tax                0
Insurance                    0
Hypothication                0
Total Vehical Cost           0
Ridding Cost                 0
Accessories                  0
Total Cost to Ved Motors     0
Selling Price                0
Net Earning                  0
Payment Type                 0
CASH Payment                 0
Loan Amount                  5
EMI Month                    4
EMI Amount                   2
Receipt No.1                 0
Booking Amount               0
Receipt No.2                 0
Amount                       0
Receipt No.3                 0
Amount.1                     0
Receipt No.4                 0
Amount.2                     0
Total Paid Amount            0
DP Balance                   0
Disbursed Date              14
Disbursed Amount            10
Net Earning loan             0
Total Earning                0
Balance Remark              18
Vehical RTO No.              9
Date of Birth                5
Address                     18
dtype: int64

In [137]:
df.isnull().sum().sort_values(ascending=False)

Address                     18
Balance Remark              18
Disbursed Date              14
Disbursed Amount            10
Vehical RTO No.              9
Date of Birth                5
Loan Amount                  5
EMI Month                    4
Vehical Engine No.           2
EMI Amount                   2
Vehical Chassis No.          1
Net Earning loan             0
Total Earning                0
Total Paid Amount            0
Amount.2                     0
Receipt No.4                 0
Amount.1                     0
Receipt No.3                 0
Amount                       0
Receipt No.2                 0
Booking Amount               0
Receipt No.1                 0
DP Balance                   0
Unnamed: 0                   0
Booking Date                 0
Payment Type                 0
Customer Name                0
Mobile No.                   0
Company                      0
Model                        0
Colour                       0
Dealer                       0
Vehical Base                 0
Dealer Price                 0
E Payment Tax                0
Insurance                    0
Hypothication                0
Total Vehical Cost           0
Ridding Cost                 0
Accessories                  0
Total Cost to Ved Motors     0
Selling Price                0
Net Earning                  0
CASH Payment                 0
dtype: int64

## 4. Checking Unique Values

I checked unique values in important text columns to find
inconsistencies and different spellings.

In [141]:
df["Customer Name"].unique()

array(['SAPANA SALUNKHE ', 'HEMANGI SHELAR  ', 'ANIKET SURYWANSI  ',
       'TEJAS BHURE ', 'SAGAR PALSE  ', 'SAMEER  HAREKAR  ',
       'JITESH  PATIL  ', 'JAYWANT MORE  ', 'SANTOSH GOLLAR  ',
       'MAHENDRA KENI  no ', 'ATUL VISHWAKARMA ', 'RAHUL SUMRA ',
       'PRASHANT AMBRE', 'LUXMAN HINKULE  ', 'ABHISHEK UTEKAR  ',
       'suresh bagwan  ', 'ROSHAN SHELAR', 'UTTAM CHOUDARI  '],
      dtype=object)

In [139]:
df["Company"].unique()

array(['T-V-S', 'BGUSS E', 'Honda', 'SARVODAYA', 'RIA SUZUKI', 'HERO',
       'MAYURAUTO'], dtype=object)

In [140]:
df["Model"].unique()

array(['JUPITER ZX', 'BGUS A2', 'CB SHINE', 'ACTIVA6G', 'UNICON',
       'BGUS B8', 'BAJAJCT 110', 'UNICON  160', 'ACSESS125SPL',
       'BGUSS B8', 'SPLENDERPLUS', 'ACTIVA6G DULX', 'HF DELUX', 'APPACHI',
       'SP SHINE'], dtype=object)

In [142]:
df["Vehical Base"].unique()

array(['ON ROAD', 'ONROAD', 'BASIC'], dtype=object)

In [143]:
df["Payment Type"].unique()

array(['LOAN', 'CASH', 'Loan'], dtype=object)

## 5. Experiment — Cleaning Customer Names

I noticed that customer names were not consistently formatted.

I experimented with string methods and found that `.str.title()`
was useful for capitalizing the first letter of each word.

In [144]:
df["Customer Name"].head()

0      SAPANA SALUNKHE
1      HEMANGI SHELAR
2    ANIKET SURYWANSI
3          TEJAS BHURE
4         SAGAR PALSE
Name: Customer Name, dtype: object

In [145]:
df["Customer Name"] = (
    df["Customer Name"]
    .astype("string")
    .str.strip()
    .str.title()
)

df["Customer Name"].head()

0     Sapana Salunkhe
1      Hemangi Shelar
2    Aniket Surywansi
3         Tejas Bhure
4         Sagar Palse
Name: Customer Name, dtype: string

## 6. Cleaning Company Names

I found unnecessary characters such as `-` and inconsistent
capitalization in company names.

I removed the unnecessary `-` and standardized the capitalization.

Bgauss is the correct spelling for the company name.

In [146]:
df["Company"].unique()

array(['T-V-S', 'BGUSS E', 'Honda', 'SARVODAYA', 'RIA SUZUKI', 'HERO',
       'MAYURAUTO'], dtype=object)

In [147]:
df["Company"] = (
    df["Company"]
    .astype("string")
    .str.strip()
    .str.replace("-", "", regex=False)
    .str.title()
)

# Correct company spelling
df["Company"] = df["Company"].replace(
    {
        "Bguss": "Bgauss",
        "Bgauss": "Bgauss"
    }
)

df["Company"].unique()

<StringArray>
['Tvs', 'Bguss E', 'Honda', 'Sarvodaya', 'Ria Suzuki', 'Hero', 'Mayurauto']
Length: 7, dtype: string

## 7. Cleaning Vehicle Base

I found different versions of the same vehicle base:

- ON ROAD
- ONROAD
- BASIC

I standardized them into:

- On Road
- Basic

In [148]:
df["Vehical Base"].unique()

array(['ON ROAD', 'ONROAD', 'BASIC'], dtype=object)

In [149]:
df["Vehical Base"] = (
    df["Vehical Base"]
    .astype("string")
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
    .str.title()
)

df["Vehical Base"] = (
    df["Vehical Base"]
    .str.replace(
        r"^On\s*Road$",
        "On Road",
        case=False,
        regex=True
    )
    .str.replace(
        r"^Basic$",
        "Basic",
        case=False,
        regex=True
    )
)

df["Vehical Base"].unique()

<StringArray>
['On Road', 'Basic']
Length: 2, dtype: string

## 8. Cleaning Vehicle Models

I standardized model names by removing unnecessary spaces
and applying consistent capitalization.

In [151]:
df["Model"] = (
    df["Model"]
    .astype("string")
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
    .str.title()
)

df["Model"].unique()

<StringArray>
[   'Jupiter Zx',       'Bgus A2',      'Cb Shine',      'Activa6G',
        'Unicon',       'Bgus B8',   'Bajajct 110',    'Unicon 160',
  'Acsess125Spl',      'Bguss B8',  'Splenderplus', 'Activa6G Dulx',
      'Hf Delux',       'Appachi',      'Sp Shine']
Length: 15, dtype: string

## 9. Standardizing Payment Type

I found different capitalization such as CASH, Cash, LOAN and Loan.

I standardized them to uppercase so that the values are consistent.

In [152]:
df["Payment Type"].unique()

array(['LOAN', 'CASH', 'Loan'], dtype=object)

In [153]:
df["Payment Type"] = (
    df["Payment Type"]
    .astype("string")
    .str.strip()
    .str.upper()
)

df["Payment Type"].unique()

<StringArray>
['LOAN', 'CASH']
Length: 2, dtype: string

## 10. Cleaning Mobile Numbers

I removed unnecessary characters such as spaces, `+`, `-`
and brackets from mobile numbers.

In [154]:
df["Mobile No."] = (
    df["Mobile No."]
    .astype("string")
    .str.replace(r"\D", "", regex=True)
)

df["Mobile No."].head()

0    9082384445
1    9869658575
2    9819169457
3    9702403349
4    8879417136
Name: Mobile No., dtype: string

## 11. Cleaning Vehicle Engine Numbers

The Vehicle Engine Number column contains a combination of
letters and numbers.

I only removed `-` characters and kept the letters and numbers
unchanged because these values are identifiers.

In [ ]:
df["Vehical Engine No."] = (
    df["Vehical Engine No."]
    .astype("string")
    .str.strip()
    .str.replace("-", "", regex=False)
)

## 12. Cleaning Vehicle Chassis Numbers

The chassis number is also an identifier, so I removed only
unnecessary `-` characters without changing the actual values.

In [156]:
df["Vehical Chassis No."] = (
    df["Vehical Chassis No."]
    .astype("string")
    .str.strip()
    .str.replace("-", "", regex=False)
)

## 13. Working with Date Columns

I converted Booking Date and Date of Birth into Pandas datetime
format so they can be used properly for future analysis.

In [157]:
df["Booking Date"] = pd.to_datetime(
    df["Booking Date"],
    errors="coerce"
)

df["Date of Birth"] = pd.to_datetime(
    df["Date of Birth"],
    errors="coerce"
)

df[["Booking Date", "Date of Birth"]].head()

  Booking Date Date of Birth
0   2021-10-15    1980-08-12
1   2021-10-15    1984-11-15
2   2021-12-16    1999-09-18
3   2021-10-17    1982-12-21
4   2021-10-17    1994-09-24

In [9]:
import pandas as pd

input_file = r"C:\Users\Shravani Patane\Downloads\Ved_Motors_Project\Ved_Motors_Cleaned_Final.xlsx"

df = pd.read_excel(input_file)

df.head()

,Booking Date,Customer Name,Mobile No.,Company,Model,Colour,Dealer,Vehical Chassis No.,Vehical Engine No.,Vehical Base,...,Receipt No.4,Amount.2,Total Paid Amount,DP Balance,Disbursed Date,Disbursed Amount,Net Earning loan,Total Earning,Vehical RTO No.,Date of Birth
0,2021-10-15,Sapana Salunkhe,9082384445,TVS,Jupiter Zx,GREENISH BLUE,AUTORACE,MD626CG59M1L09923,DG5LM1802951,On Road,...,0,0,21000,0,2021-10-15 00:00:00,72290,5290,91290,MH04KZ6980,1980-08-12 00:00:00
1,2021-10-15,Hemangi Shelar,9869658575,BGUSS E,Bgus A2,GREY,BGUSS,A21BG000079,BBD00103,On Road,...,0,0,68500,0,Not Provided,Not Provided,0,2200,Not Provided,1984-11-15 00:00:00
2,2021-10-17,Tejas Bhure,9702403349,Honda,Cb Shine,BLACK RED,VIHAN,ME4JC85AKMG033594,JC85EG1037927,On Road,...,0,0,89000,0,Not Provided,Not Provided,0,2000,MH04KY5509,1982-12-21 00:00:00
3,2021-10-17,Sagar Palse,8879417136,BGUSS E,Bgus A2,BLUE,BGUSS,A21BG000081,BBD000295,On Road,...,0,0,30000,0,0,Not Provided,-39000,-35300,Not Provided,1994-09-24 00:00:00
4,2021-10-17,Sameer Harekar,7977716284,Honda,Activa6G,BIUE,VIHAN,ME4JF918KMW036572,JF91E-W-5036537,On Road,...,0,0,86000,0,Not Provided,Not Provided,0,2200,MH04KY6337,1975-08-18 00:00:00

## 14. Handling Missing Values

After inspecting the missing values, I decided to represent
remaining empty cells as `Not Provided` in the final cleaned
dataset.

In [10]:
df = df.fillna("Not Provided")

df.isnull().sum().sum()

np.int64(0)

## 15. Final Data Check

I checked the cleaned dataset again to make sure the changes
were successfully applied.

In [11]:
df.shape

(17, 41)

In [ ]:
df.head()

In [13]:
df["Company"].unique()

array(['TVS', 'BGUSS E', 'Honda', 'SARVODAYA', 'RIA SUZUKI', 'HERO',
       'MAYURAUTO'], dtype=object)

In [14]:
df["Company"].unique()

array(['TVS', 'BGUSS E', 'Honda', 'SARVODAYA', 'RIA SUZUKI', 'HERO',
       'MAYURAUTO'], dtype=object)

In [15]:
df["Vehical Base"].unique()

array(['On Road', 'Basic'], dtype=object)

In [16]:
df["Company"] = (
    df["Company"]
    .astype("string")
    .str.strip()
    .str.title()
)

df["Company"] = df["Company"].replace(
    "Bguss E",
    "Bgauss E"
)

df["Company"].unique()

<StringArray>
['Tvs', 'Bgauss E', 'Honda', 'Sarvodaya', 'Ria Suzuki', 'Hero', 'Mayurauto']
Length: 7, dtype: string

In [26]:
df["Dealer"] = (
    df["Dealer"]
    .astype("string")
    .str.strip()
    .str.title()
)
df["Dealer"] = df["Dealer"].replace(
    "Bguss",
    "Bgauss"
)
df["Colour"] = (
    df["Colour"]
    .astype("string")
    .str.strip()
    .str.title()
)
df["Dealer"].unique()

<StringArray>
[  'Autorace',     'Bgauss',      'Vihan',  'Sarvodaya',       'Gati',
  'Riasuzuki',  'Automiles', 'Mayur Auto',      'Honda']
Length: 9, dtype: string

In [30]:
df["Booking Date"] = pd.to_datetime(
    df["Booking Date"],
    errors="coerce",
    dayfirst=True
).dt.strftime("%d-%m-%Y")

df["Date of Birth"] = pd.to_datetime(
    df["Date of Birth"],
    errors="coerce",
    dayfirst=True
).dt.strftime("%d-%m-%Y")

## 16. Final Data Check

After completing the cleaning process, I performed a final check
to make sure the data was consistent and the changes were applied
correctly.

I checked the dataset shape, previewed the cleaned data, and verified
important columns and remaining missing values.

In [31]:
print("Dataset Shape:", df.shape)

df.head()

Dataset Shape: (17, 41)

,Booking Date,Customer Name,Mobile No.,Company,Model,Colour,Dealer,Vehical Chassis No.,Vehical Engine No.,Vehical Base,...,Receipt No.4,Amount.2,Total Paid Amount,DP Balance,Disbursed Date,Disbursed Amount,Net Earning loan,Total Earning,Vehical RTO No.,Date of Birth
0,15-10-2021,Sapana Salunkhe,9082384445,Tvs,Jupiter Zx,Greenish Blue,Autorace,MD626CG59M1L09923,DG5LM1802951,On Road,...,0,0,21000,0,2021-10-15 00:00:00,72290,5290,91290,MH04KZ6980,08-12-1980
1,15-10-2021,Hemangi Shelar,9869658575,Bgauss E,Bgus A2,Grey,Bgauss,A21BG000079,BBD00103,On Road,...,0,0,68500,0,Not Provided,Not Provided,0,2200,Not Provided,NaN
2,17-10-2021,Tejas Bhure,9702403349,Honda,Cb Shine,Black Red,Vihan,ME4JC85AKMG033594,JC85EG1037927,On Road,...,0,0,89000,0,Not Provided,Not Provided,0,2000,MH04KY5509,NaN
3,17-10-2021,Sagar Palse,8879417136,Bgauss E,Bgus A2,Blue,Bgauss,A21BG000081,BBD000295,On Road,...,0,0,30000,0,0,Not Provided,-39000,-35300,Not Provided,NaN
4,17-10-2021,Sameer Harekar,7977716284,Honda,Activa6G,Biue,Vihan,ME4JF918KMW036572,JF91E-W-5036537,On Road,...,0,0,86000,0,Not Provided,Not Provided,0,2200,MH04KY6337,NaN

## 16. Final Data Check

Before exporting the final dataset, I performed one last cleaning
and validation step.

The `Disbursed Date` and `Disbursed Amount` columns were removed
because they were not required for this project.

I also corrected the `Bgus` spelling in the Model column to `Bgauss`
while keeping the rest of each model name unchanged.

For example:
- Bgus A2 → Bgauss A2
- Bgus A8 → Bgauss A8
- Bgus B2 → Bgauss B2

Finally, I checked the cleaned dataset before exporting it.

In [32]:
# Remove unnecessary columns
df = df.drop(
    columns=["Disbursed Date", "Disbursed Amount"],
    errors="ignore"
)

# Correct Bgus spelling in every Model value
# Keeps the rest of the model unchanged
df["Model"] = (
    df["Model"]
    .astype("string")
    .str.replace(
        r"Bgus",
        "Bgauss",
        case=False,
        regex=True
    )
)

# Final check
print("Dataset Shape:", df.shape)

print("\nModel values:")
print(df["Model"].unique())

print("\nRemaining empty cells:")
print(df.isnull().sum().sum())

df.head()

Dataset Shape: (17, 39)

Model values:
<StringArray>
[   'Jupiter Zx',     'Bgauss A2',      'Cb Shine',      'Activa6G',
        'Unicon',     'Bgauss B8',   'Bajajct 110',    'Unicon 160',
  'Acsess125Spl',    'Bgausss B8',  'Splenderplus', 'Activa6G Dulx',
      'Hf Delux',       'Appachi',      'Sp Shine']
Length: 15, dtype: string

Remaining empty cells:
13

,Booking Date,Customer Name,Mobile No.,Company,Model,Colour,Dealer,Vehical Chassis No.,Vehical Engine No.,Vehical Base,...,Receipt No.3,Amount.1,Receipt No.4,Amount.2,Total Paid Amount,DP Balance,Net Earning loan,Total Earning,Vehical RTO No.,Date of Birth
0,15-10-2021,Sapana Salunkhe,9082384445,Tvs,Jupiter Zx,Greenish Blue,Autorace,MD626CG59M1L09923,DG5LM1802951,On Road,...,0,0,0,0,21000,0,5290,91290,MH04KZ6980,08-12-1980
1,15-10-2021,Hemangi Shelar,9869658575,Bgauss E,Bgauss A2,Grey,Bgauss,A21BG000079,BBD00103,On Road,...,0,0,0,0,68500,0,0,2200,Not Provided,NaN
2,17-10-2021,Tejas Bhure,9702403349,Honda,Cb Shine,Black Red,Vihan,ME4JC85AKMG033594,JC85EG1037927,On Road,...,0,0,0,0,89000,0,0,2000,MH04KY5509,NaN
3,17-10-2021,Sagar Palse,8879417136,Bgauss E,Bgauss A2,Blue,Bgauss,A21BG000081,BBD000295,On Road,...,0,0,0,0,30000,0,-39000,-35300,Not Provided,NaN
4,17-10-2021,Sameer Harekar,7977716284,Honda,Activa6G,Biue,Vihan,ME4JF918KMW036572,JF91E-W-5036537,On Road,...,0,0,0,0,86000,0,0,2200,MH04KY6337,NaN

In [36]:
df["Colour"] = (
    df["Colour"]
    .astype("string")
    .str.replace(
        r"Biue",
        "Blue",
        case=False,
        regex=True
    )
)

In [38]:
# ============================================================
# FINAL CORRECTIONS
# ============================================================

# 1. Colour: biack → Black
df["Colour"] = df["Colour"].replace(
    r"Biack",
    "Black",
    regex=True
)

# 2. Model corrections
# Bajajct → Bajaj CT
# Apachi → Apache
df["Model"] = (
    df["Model"]
    .astype("string")
    .str.replace(
        r"Bajajct",
        "Bajaj CT",
        case=False,
        regex=True
    )
    .str.replace(
        r"Apachi",
        "Apache",
        case=False,
        regex=True
    )
)

# 3. Vehicle Engine Number:
# Remove "-" but keep letters and numbers unchanged
df["Vehical Engine No."] = (
    df["Vehical Engine No."]
    .astype("string")
    .str.replace("-", "", regex=False)
)

# 4. Date of Birth:
# Convert empty/missing values to "Not Provided"
df["Date of Birth"] = df["Date of Birth"].replace(
    ["", " ", "NaN", "nan", "NaT"],
    "Not Provided"
)

df["Date of Birth"] = df["Date of Birth"].fillna("Not Provided")


# ============================================================
# CHECK THE FINAL CHANGES
# ============================================================

print("Colour values:")
print(df["Colour"].unique())

print("\nModel values:")
print(df["Model"].unique())

print("\nDate of Birth:")
print(df["Date of Birth"].unique())

print("\nVehicle Engine Numbers:")
print(df["Vehical Engine No."].head())

Colour values:
<StringArray>
['Greenish Blue',          'Grey',     'Black Red',          'Blue',
         'Black',      'Mat Grey',     'Red Black',    'Black Grey',
         'White',   'Black White',   'Black Green']
Length: 11, dtype: string

Model values:
<StringArray>
[   'Jupiter Zx',     'Bgauss A2',      'Cb Shine',      'Activa6G',
        'Unicon',     'Bgauss B8',  'Bajaj CT 110',    'Unicon 160',
  'Acsess125Spl',    'Bgausss B8',  'Splenderplus', 'Activa6G Dulx',
      'Hf Delux',       'Appachi',      'Sp Shine']
Length: 15, dtype: string

Date of Birth:
['08-12-1980' 'Not Provided' '01-01-1998' '07-02-1968' '08-03-1979']

Vehicle Engine Numbers:
0     DG5LM1802951
1         BBD00103
2    JC85EG1037927
3        BBD000295
4    JF91EW5036537
Name: Vehical Engine No., dtype: string

In [39]:
df["Model"] = df["Model"].replace("Appachi", "Apache")

In [40]:
df["Model"].unique()

<StringArray>
[   'Jupiter Zx',     'Bgauss A2',      'Cb Shine',      'Activa6G',
        'Unicon',     'Bgauss B8',  'Bajaj CT 110',    'Unicon 160',
  'Acsess125Spl',    'Bgausss B8',  'Splenderplus', 'Activa6G Dulx',
      'Hf Delux',        'Apache',      'Sp Shine']
Length: 15, dtype: string

## 17. Exporting the Final Cleaned Dataset

After completing all the cleaning, standardization and final
corrections, I exported the cleaned dataset into an Excel file.

The final dataset is now ready for further analysis and visualization.

In [41]:
output_file = r"C:\Users\Shravani Patane\Downloads\Ved_Motors_Project\Ved_Motors_Cleaned_Final.xlsx"

df.to_excel(output_file, index=False)

print("✅ FINAL CLEANED FILE EXPORTED SUCCESSFULLY!")
print("Saved at:", output_file)

✅ FINAL CLEANED FILE EXPORTED SUCCESSFULLY!
Saved at: C:\Users\Shravani Patane\Downloads\Ved_Motors_Project\Ved_Motors_Cleaned_Final.xlsx

# Conclusion

This project helped me learn and practice Pandas by working with
a real-world vehicle sales dataset.

During the cleaning process, I experimented with different Pandas
methods to:

- Load and inspect an Excel dataset
- Understand the structure and data types
- Identify and handle missing values
- Remove unnecessary columns and records
- Clean and standardize customer names
- Standardize company and dealer names
- Correct spelling inconsistencies
- Standardize vehicle models
- Standardize vehicle base values such as On Road and Basic
- Clean mobile numbers
- Remove unnecessary characters from vehicle identifiers
- Work with date columns
- Replace missing values with "Not Provided"
- Validate the cleaned dataset
- Export the final cleaned dataset to Excel

This project helped me understand how Pandas can be used to
clean messy real-world data and prepare it for further analysis,
visualization and future data science projects.